import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import dotenv from "dotenv";
import path from "path";

// Load environment variables from .env file
dotenv.config();

// Prepare output file path (defaults to the repo root when OUTPUT_PATH is unset)
const outFilePath = path.join(process.env.OUTPUT_PATH ?? ".", "main.js");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	// onnxruntime-web (pulled in by parakeet.js) ships modern syntax that
	// cannot be transpiled down to es2018; Obsidian's Electron supports es2022
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outFilePath,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
